### ISSUE TITLE
Does nginx-http-rdns work correctly in conjunction with the proxy module? 

### ISSUE THREAD

**Issue by uiltondutra** [flant/nginx-http-rdns#1]
It seems that in some occasions the fact that nginx-http-rdns uses Nginx resolver mess with Nginx ability to communicate with the upstream. For a production server running fine for months, when I enable nginx-http-rdns I start getting 404 error messages for a bunch of requests because Nginx is trying to access local files and is not passing along to the upstream. Any ideas?

PS: I did a fork and added the ability to resolve correctly using x_forwarded_for when available (heavily inspired on GeoIP module implementation).

**Comment by aarvee11** [comment]
@uiltondutra what was the solution you finally went for? In my case, the rdns is not even kicking in proxy mode in conjunction with proxy !
