### ISSUE TITLE
Caching DNS Lookup

### ISSUE THREAD

**Issue by Haelle** [flant/nginx-http-rdns#14]
Does `rdns` perform caching when resolving (reverse) DNS lookup ?

I found this [comment](https://github.com/flant/nginx-http-rdns/issues/10#issuecomment-285978697), it suggest to me that yes. If so it could be a good idea to mention it in the README. wdyt ?

**Comment by alpha-and-omega** [comment]
Yes it uses nginx core resolver cache, for a maximum 30 seconds or DNS response TTL.
And yes, this should be mentioned in README.

**Comment by distol** [comment]
Thanks. PR would be highly appreciated.
