### ISSUE TITLE
reverse proxy problem.

### ISSUE THREAD

**Issue by fromhell39** [flant/nginx-http-rdns#17]
apply nginx.conf
rdns on; 

option error none rdns ips for using hidden browsers.

in the use Nginx reverse proxy 

proxy_pass http://url;

Please resolve this bug for this great 3rd module. Because with this module except googlebots and many bots ddos waf and captcha guard systems.

Please..

**Comment by 9mido** [comment]
@fromhell39 why did you close this issue? How did you resolve it?
